# People {-#people}

This project would not be possible without dedicated collaborators.

## University of British Columbia {-#ubc}

### Prof. Nicholas Coops, *project lead* {-#ncc}

[Professor Nicholas Coops](https://forestry.ubc.ca/faculty-profile/nicholas-coops/) holds a Canada Research Chair in Remote Sensing (Tier 1) at UBC. He has published >460 total referenced peer-reviewed journal publications and is internationally recognised as a scientific leader in the field of remote sensing. He was the principal investigator of the AWARE project, a 5-year research project focused on developing LIDAR applications in Canada for forestry applications. He is a co-author on the Canadian Forest Service LIDAR best practice guide series, the most downloaded CFS information handbook ever, focused on LIDAR data processing. In 2020 he was the co-receipt of the Marcus Wallenberg prize for scientific achievements contributing to significantly broadening knowledge and technical development within the field of Forestry.

Coops has lead a previous, successful Forestry Futures Trust Ontario grant investigating the application of SPL data for forest inventory and plot stratification in Ontario. 

#### Responsibilities {-#responsibilities-ncc}

Coops as the PI will manage the budget, an overall assignment of students and researchers to the project. A research scientist (RS) will be based and supervised by Coops at UBC. At the completion of the project the RS at UBC will ensure the software is able to be released openly and publicly to allow other forest management areas in Ontario covered by SPL data to be applied and for use by Provincial staff.

### Ethan Berman, *research scientist* {-#eb}

[Ethan Berman](linkedin.com/in/ethan-berman) is a research scientist in the Integrated Remote Sensing Studio (IRSS) at UBC. He has a background in mathematics and remote sensing, and has worked extensively with large spatial datasets, developing novel approaches and building models to answer questions relating to forests, snow, vegetation, and climate change. Ethan received his MSc in 2019 under the supervision of Prof. Coops and before starting work on this project was a consultant for the United States Geological Survey, constructing, curating, and managing spatial datasets for a team of ecologists. 

#### Responsibilities {-#responsibilities-eb}

Berman will be responsible for data management, algorithm development and testing, and delivery of open source software tools to the project partners. He will be supervised by Prof. Coops at UBC.

## Rayonier Advanced Materials (RYAM) Forest Management {-#ryam}

### Chris McDonell, *partner* {-#cm}

[Chris McDonell](linkedin.com/in/chris-mcdonell-45759113) is the manager of aboriginal and environmental relations at RYAM. He is accountable for relations between RYAM and First Nation and Metis communities in Ontario and Quebec. He is also the coordinator of forest certification standard implementation (FSC) and liaison with various public, private and community organizations.

### Grant McCartney, *partner* {-#gm}

[Grant McCartney](https://ca.linkedin.com/in/grantmccartneygis) was a spatial analyst and forest information systems coordinator with RYAM Forest Management. He recently transitioned to a role at Forsite Consultants. He performed spatial analysis in support of forest management planning (FMP) and forestry operations on the Gordon Cosens, Romeo Malette and Martel – Magpie Forests in Northeastern Ontario, Canada and led the acquisition of remotely sensed data including Digital Aerial Photogrammetry (DAP) and LiDAR for RYAM. He has been an industrial partner in numerous research efforts including: the Assessment of Wood Attributes for REmote sensing (AWARE) project, CWFC – FIP , past FFT - KKTD projects and the recently approved Silv@21.

#### Responsibilities {-#responsibilities-ryam}

We will work with RYAM Forest Management at a number of their forest management areas where FRI data and EFi data exist. RYAM partners will provide plot data, SPL and any other relevant datasets over the areas to ensure accurate model development. They will also attend project meetings, assess model accuracy with RYAM staff and test developed software as required. 

## Ontario Ministry of Northern Development, Mines, Natural Resources and Forestry {-#ministry}

### Ian Sinclair, *partner* {-#is}

[Ian Sinclair](linkedin.com/in/ian-sinclair-984929a4) is a terrestrial landscape analyst with the Ontario Ministry of Northern Development, Mines, Natural Resources and Forestry, where he is responsible for the development of remotely sensed inventory and landscape level monitoring and reporting programs. His focus includes the development of LiDAR attributes and remotely sensed applications to support a continuous forest inventory program. Ian also coordinates the acquisition program of the Ministry’s SPL program and supports the operational aspects of the Vegetation Sampling Network Protocol for development of LiDAR based forest inventories.

### Derek Landry, *partner* {-#dl}

[Derek Landry](linkedin.com/in/derek-landry-4a860b212) is the management coordinator of Ontario’s Forest Resources Inventory (FRI) Unit in the Ministry of Northern Development, Mines, Natural Resources and Forestry, where he is leading the modernization of provincial forest inventory and land cover mapping programs. Derek has been working in the Ontario Public Service for 25 years. Prior to joining the FRI unit, Derek managed the development and implementation of recommendations to modernize provincial scale fisheries, wildlife, and vegetation monitoring programs, through the Integrated Monitoring Framework initiative.

### Geordie Robere-McGugan, *partner* {-#grm}

[Geordie Robere-McGugan](linkedin.com/in/geordie-robere-mcgugan-b5b6aa3) is the Inventory Development Specialist with the Ontario Ministry of Northern Development, Mines, Natural Resources and Forestry and the lead on the modernization of the Forest Resources Inventory ensuring the inventory products meet the Provincial Policy Framework. 

#### Responsibilities {-#responsibilities-ministry}

Sinclair, Landry and Robere-McGugan all of whom are in the Ontario Provincial government with significant expertise in the FRI mapping process, SPL data capture and specifications and iventory Development Specialist. Ensuring that government partners are on the project team ensures that the outcomes will have immediate uptake by other users within the Ministry thereby ensuring successful technology transfer and knowledge exchange. All three will be available for project update meetings, advice to the PDF and attending virtual call on project updates. All three will be available to test versions of the developed open source code and help ensure documentation is easy to access and appropriate. 