# **2** People {-#people}

This project would not be possible without dedicated collaborators.

## **2.1** University of British Columbia {-#ubc}

### Prof. Nicholas Coops, *project lead* {-#ncc}

[Professor Nicholas Coops](https://forestry.ubc.ca/faculty-profile/nicholas-coops/) holds a Canada Research Chair in Remote Sensing (Tier 1) at UBC. He has published >460 total referenced peer-reviewed journal publications and is internationally recognised as a scientific leader in the field of remote sensing. He was the principal investigator of the AWARE project, a 5-year research project focused on developing LiDAR applications in Canada for forestry applications. He is a co-author of the Canadian Forest Service LiDAR best practice guide series, the most downloaded CFS information handbook ever, focused on LiDAR data processing. In 2020 he was the co-recipient of the Marcus Wallenberg prize for scientific achievements contributing to significantly broadening knowledge and technical development within the field of Forestry.

Coops has lead a previous, successful Forestry Futures Trust Ontario grant investigating the application of SPL data for forest inventory and plot stratification in Ontario. 

#### Responsibilities {-#responsibilities-ncc}

As the principal investigator, Coops will manage the budget and supervise Ethan Berman, the research scientist working on the project. At the completion of the project Berman will ensure the software is suitable for open and public release, allowing the methods to be applied to other forest management areas in Ontario covered by SPL data and to be used by Provincial staff.

### Ethan Berman, *research scientist* {-#eb}

[Ethan Berman](https://linkedin.com/in/ethan-berman) is a research scientist in the Integrated Remote Sensing Studio (IRSS) at UBC. He has a background in mathematics and remote sensing, and has worked extensively with large spatial datasets, developing novel approaches and building models to answer questions relating to forests, snow, vegetation, and climate change. Ethan received his MSc in 2019 under the supervision of Prof. Coops and before starting work on this project was a consultant for the United States Geological Survey, constructing, curating, and managing spatial datasets for a team of ecologists. 

#### Responsibilities {-#responsibilities-eb}

Berman will be responsible for data management, algorithm development and testing, and delivery of open source software tools to the project partners. He will be supervised by Prof. Coops at UBC.

## **2.2** GreenFirst Forest Products {-#greenfirst}

### Chris McDonell, *partner* {-#cm}

[Chris McDonell](https://linkedin.com/in/chris-mcdonell-45759113) is the Chief Forester for Ontario at GreenFirst Forest Products. He is accountable for relations between GreenFirst and First Nation and Metis communities in Ontario and Quebec. He is also the coordinator of forest certification standard implementation (FSC) and liaison with various public, private and community organizations.

### Grant McCartney, *partner* {-#gm}

[Grant McCartney](https://ca.linkedin.com/in/grantmccartneygis) was a spatial analyst and forest information systems coordinator with RYAM Forest Management (now GreenFirst Forest Products). He recently transitioned to a role at Forsite Consultants. He performed spatial analysis in support of forest management planning (FMP) and forestry operations on the Gordon Cosens, Romeo Malette and Martel – Magpie Forests in Northeastern Ontario, Canada and led the acquisition of remotely sensed data including Digital Aerial Photogrammetry (DAP) and LiDAR for RYAM. He has been an industry partner in numerous research efforts including: the Assessment of Wood Attributes for REmote sensing (AWARE) project, CWFC – FIP , past FFT - KKTD projects and the recently approved Silv@21.

#### Responsibilities {-#responsibilities-greenfirst}

We will work with GreenFirst Forest Products at a number of their forest management areas where FRI data and EFI data exist. GreenFirst partners will provide plot data, SPL and any other relevant datasets over the areas to ensure accurate model development. They will also attend project meetings, assess model accuracy with GreenFirst staff and test developed software as required. 

## **2.3** Ontario Ministry of Natural Resources and Forestry {-#ministry}

### Ian Sinclair, *partner* {-#is}

[Ian Sinclair](https://linkedin.com/in/ian-sinclair-984929a4) is a terrestrial landscape analyst with the Ontario Ministry of Natural Resources and Forestry, where he is responsible for the development of remotely sensed inventory and landscape level monitoring and reporting programs. His focus includes the development of LiDAR attributes and remotely sensed applications to support a continuous forest inventory program. Ian also coordinates acquisition of the Ministry’s SPL program and supports the operational aspects of the Vegetation Sampling Network Protocol for development of LiDAR based forest inventories.

### Geordie Robere-McGugan, *partner* {-#grm}

[Geordie Robere-McGugan](https://linkedin.com/in/geordie-robere-mcgugan-b5b6aa3) is the Inventory Development Specialist at the Ontario Ministry of Natural Resources and Forestry and the lead on the modernization of the Forest Resources Inventory ensuring the inventory products meet the Provincial Policy Framework. 

#### Responsibilities {-#responsibilities-ministry}

Sinclair and Robere-McGugan have significant expertise in the FRI mapping process, SPL data capture and inventory development. Including government partners on the project team ensures that the outcomes will have immediate uptake by other users within the Ministry and there will be a successful technology transfer and knowledge exchange. Sinclair and Robere-McGugan will be available for project update meetings and to give advice to the research team. They will also be available to test versions of the developed open source code and help ensure documentation is easy to access and appropriate.

## **2.4** Laval University {-#laval}

### Alexis Achim, *advisor* {-#aachim}

[Alexis Achim](https://www.sbf.ulaval.ca/alexis-achim) is a professor in the Faculty of Forestry, Geography and Geomatics at Laval University. His research interests are at the interface between forest management and wood science. He specializes in modelling the effects of forest management practices on wood fibre attributes. He was the scientific leader of the research theme on wood properties modelling within ForValueNet, the NSERC strategic Network on forest management for value-added products.

#### Responsibilities {-#responsibilities-aachim}

Achim will serve as a project advisor, providing valuable feedback to the development and implementation of scientific methods used to achieve the project objectives.